{
  "name": "Junyss-Graphql-Test",
  "schemaPath": "src/main/resources/graphql/*.graphqls",
  "extensions": {}
}

{
  "name": "Graphql-Example",
  "schemaPath": "src/main/resources/graphql/*.graphqls",
  "extensions": {}
}